### PR TITLE
DEV TO RELEASE | add undefined guard for badly formatted RD names

### PR DESCRIPTION
**Pull request by jeffzyliu**
# Description

One to two sentence description.

## Type of Change

- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Documentation update

## Checklist

- [ ] Unit/integration tests
- [ ] Documentation

## Tickets

- [Issue Number](Link)

## Screenshots

Please attach any design screenshots if UI update.

### CODE REVIEW

**Review by tmonfre — APPROVED** [review]
please wait to merge until checks pass. thanks for this! 🚀

**Comment by jeffzyliu** [comment]
@tmonfre I think buildkite isn't active anymore or something (checks are never finishing). Should we change up the CI to use github actions or something?

**Comment by tmonfre** [comment]
@jeffzyliu ah yes sorry dartmouth servers shut down buildkite now that we switched to using thayer. can you change it to github actions? i can help if you need it

**Comment by jeffzyliu** [comment]
@tmonfre I'm just going to merge this now and maybe redo CI later. Don't have time atm to work on CI.

**Pull request merged**
