### PR TITLE
Title change

### PR DESCRIPTION
**Pull request by gracewanggw**
# Description

Changed name of "Trapping Data" tab to "Historical and Model Input Data".
Changed title of that page from "Trapping & Spot data" to "Historical and Model Input Data"

## Type of Change

- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Documentation update

## Checklist

- [ ] Unit/integration tests
- [ ] Documentation

## Tickets

- [#520 ](Link)

## Screenshots

Please attach any design screenshots if UI update.

### CODE REVIEW

**Comment by tmonfre** [comment]
Looks great! FYI you might want to change the nav styling to accommodate the longer name: 
image

e.g. make it all fit on one line

**Review by tmonfre — COMMENTED** [review]
Make sure you are using `yarn` and not `npm` when running the repo locally. Looks like you might have run `npm install` here instead of `yarn install`. 

There shouldn't be a `package-lock.json` file, only `yarn.lock`. You may want to remove the `package-lock.json` file from this PR and undo your changes to `package.json`.

**Review by AlejandroALopez — APPROVED** [review]
Great!

**Review by tmonfre — APPROVED** [review]
looks great!

**Pull request merged**
